// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AuthState`, `OrganizationList`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`

Future<List<String>> requireOrganization({required String email}) =>
    RustLib.instance.api.crateApiAuthRequireOrganization(email: email);

Future<ServerResponse> signOrg({required String email, required String org}) =>
    RustLib.instance.api.crateApiAuthSignOrg(email: email, org: org);

Future<ServerResponse> login({
  required String username,
  required String password,
  required String org,
}) => RustLib.instance.api.crateApiAuthLogin(
  username: username,
  password: password,
  org: org,
);

class ServerResponse {
  final String userId;
  final String username;

  const ServerResponse({required this.userId, required this.username});

  @override
  int get hashCode => userId.hashCode ^ username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerResponse &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          username == other.username;
}
