// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `find_best_encoder`, `get_platform_zero_copy_caps`, `new`, `to_gst_element_name`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EncoderQuality`, `PIPELINE_MANAGER`, `PipelineManager`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `eq`, `fmt`, `initialize`

Future<String> initGstreamer() =>
    RustLib.instance.api.crateApiMediaInitGstreamer();

Future<String> startScreenRecording({
  required String id,
  required String sinkPath,
}) => RustLib.instance.api.crateApiMediaStartScreenRecording(
  id: id,
  sinkPath: sinkPath,
);

Future<String> generateVideoThumbnail({
  required String videoPath,
  required String outputPath,
  required PlatformInt64 positionMs,
}) => RustLib.instance.api.crateApiMediaGenerateVideoThumbnail(
  videoPath: videoPath,
  outputPath: outputPath,
  positionMs: positionMs,
);

Future<Uint8List> captureLiveSnapshot({required String pipelineId}) => RustLib
    .instance
    .api
    .crateApiMediaCaptureLiveSnapshot(pipelineId: pipelineId);

Future<String> stopPipeline({required String id}) =>
    RustLib.instance.api.crateApiMediaStopPipeline(id: id);

Future<List<String>> getActiveStreams() =>
    RustLib.instance.api.crateApiMediaGetActiveStreams();
