// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `callback`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `INPUT_STATS`, `SYSTEM`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `deref`, `fmt`, `initialize`, `initialize`

Future<void> startInputMonitoring() =>
    RustLib.instance.api.crateApiMonitorStartInputMonitoring();

Future<InputStats> getAndResetInputStats() =>
    RustLib.instance.api.crateApiMonitorGetAndResetInputStats();

Future<SystemStats> getSystemStats() =>
    RustLib.instance.api.crateApiMonitorGetSystemStats();

Future<Uint8List> getMonitoringPacketFbs() =>
    RustLib.instance.api.crateApiMonitorGetMonitoringPacketFbs();

Future<List<Uint8List>> captureScreens() =>
    RustLib.instance.api.crateApiMonitorCaptureScreens();

class InputStats {
  final BigInt mouseClicks;
  final BigInt keyPresses;
  final BigInt mouseMoves;

  const InputStats({
    required this.mouseClicks,
    required this.keyPresses,
    required this.mouseMoves,
  });

  static Future<InputStats> default_() =>
      RustLib.instance.api.crateApiMonitorInputStatsDefault();

  @override
  int get hashCode =>
      mouseClicks.hashCode ^ keyPresses.hashCode ^ mouseMoves.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InputStats &&
          runtimeType == other.runtimeType &&
          mouseClicks == other.mouseClicks &&
          keyPresses == other.keyPresses &&
          mouseMoves == other.mouseMoves;
}

class SystemStats {
  final double cpuUsage;
  final BigInt memoryUsed;
  final BigInt memoryTotal;

  const SystemStats({
    required this.cpuUsage,
    required this.memoryUsed,
    required this.memoryTotal,
  });

  @override
  int get hashCode =>
      cpuUsage.hashCode ^ memoryUsed.hashCode ^ memoryTotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemStats &&
          runtimeType == other.runtimeType &&
          cpuUsage == other.cpuUsage &&
          memoryUsed == other.memoryUsed &&
          memoryTotal == other.memoryTotal;
}
