// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> uploadFileToS3({
  required String filePath,
  required String bucket,
  required String regionStr,
  required String accessKey,
  required String secretKey,
  required String s3Key,
}) => RustLib.instance.api.crateApiSyncUploadFileToS3(
  filePath: filePath,
  bucket: bucket,
  regionStr: regionStr,
  accessKey: accessKey,
  secretKey: secretKey,
  s3Key: s3Key,
);
