// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod workahub {

#[allow(unused_imports, dead_code)]
pub mod monitoring {


pub enum InputStatsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct InputStats<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for InputStats<'a> {
  type Inner = InputStats<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> InputStats<'a> {
  pub const VT_MOUSE_CLICKS: ::flatbuffers::VOffsetT = 4;
  pub const VT_KEY_PRESSES: ::flatbuffers::VOffsetT = 6;
  pub const VT_MOUSE_MOVES: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    InputStats { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args InputStatsArgs
  ) -> ::flatbuffers::WIPOffset<InputStats<'bldr>> {
    let mut builder = InputStatsBuilder::new(_fbb);
    builder.add_mouse_moves(args.mouse_moves);
    builder.add_key_presses(args.key_presses);
    builder.add_mouse_clicks(args.mouse_clicks);
    builder.finish()
  }


  #[inline]
  pub fn mouse_clicks(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(InputStats::VT_MOUSE_CLICKS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn key_presses(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(InputStats::VT_KEY_PRESSES, Some(0)).unwrap()}
  }
  #[inline]
  pub fn mouse_moves(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(InputStats::VT_MOUSE_MOVES, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for InputStats<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("mouse_clicks", Self::VT_MOUSE_CLICKS, false)?
     .visit_field::<u64>("key_presses", Self::VT_KEY_PRESSES, false)?
     .visit_field::<u64>("mouse_moves", Self::VT_MOUSE_MOVES, false)?
     .finish();
    Ok(())
  }
}
pub struct InputStatsArgs {
    pub mouse_clicks: u64,
    pub key_presses: u64,
    pub mouse_moves: u64,
}
impl<'a> Default for InputStatsArgs {
  #[inline]
  fn default() -> Self {
    InputStatsArgs {
      mouse_clicks: 0,
      key_presses: 0,
      mouse_moves: 0,
    }
  }
}

pub struct InputStatsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> InputStatsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_mouse_clicks(&mut self, mouse_clicks: u64) {
    self.fbb_.push_slot::<u64>(InputStats::VT_MOUSE_CLICKS, mouse_clicks, 0);
  }
  #[inline]
  pub fn add_key_presses(&mut self, key_presses: u64) {
    self.fbb_.push_slot::<u64>(InputStats::VT_KEY_PRESSES, key_presses, 0);
  }
  #[inline]
  pub fn add_mouse_moves(&mut self, mouse_moves: u64) {
    self.fbb_.push_slot::<u64>(InputStats::VT_MOUSE_MOVES, mouse_moves, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> InputStatsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    InputStatsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<InputStats<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for InputStats<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("InputStats");
      ds.field("mouse_clicks", &self.mouse_clicks());
      ds.field("key_presses", &self.key_presses());
      ds.field("mouse_moves", &self.mouse_moves());
      ds.finish()
  }
}
pub enum SystemStatsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SystemStats<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SystemStats<'a> {
  type Inner = SystemStats<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SystemStats<'a> {
  pub const VT_CPU_USAGE: ::flatbuffers::VOffsetT = 4;
  pub const VT_MEMORY_USED: ::flatbuffers::VOffsetT = 6;
  pub const VT_MEMORY_TOTAL: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SystemStats { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SystemStatsArgs
  ) -> ::flatbuffers::WIPOffset<SystemStats<'bldr>> {
    let mut builder = SystemStatsBuilder::new(_fbb);
    builder.add_memory_total(args.memory_total);
    builder.add_memory_used(args.memory_used);
    builder.add_cpu_usage(args.cpu_usage);
    builder.finish()
  }


  #[inline]
  pub fn cpu_usage(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SystemStats::VT_CPU_USAGE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn memory_used(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(SystemStats::VT_MEMORY_USED, Some(0)).unwrap()}
  }
  #[inline]
  pub fn memory_total(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(SystemStats::VT_MEMORY_TOTAL, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SystemStats<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<f32>("cpu_usage", Self::VT_CPU_USAGE, false)?
     .visit_field::<u64>("memory_used", Self::VT_MEMORY_USED, false)?
     .visit_field::<u64>("memory_total", Self::VT_MEMORY_TOTAL, false)?
     .finish();
    Ok(())
  }
}
pub struct SystemStatsArgs {
    pub cpu_usage: f32,
    pub memory_used: u64,
    pub memory_total: u64,
}
impl<'a> Default for SystemStatsArgs {
  #[inline]
  fn default() -> Self {
    SystemStatsArgs {
      cpu_usage: 0.0,
      memory_used: 0,
      memory_total: 0,
    }
  }
}

pub struct SystemStatsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SystemStatsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_cpu_usage(&mut self, cpu_usage: f32) {
    self.fbb_.push_slot::<f32>(SystemStats::VT_CPU_USAGE, cpu_usage, 0.0);
  }
  #[inline]
  pub fn add_memory_used(&mut self, memory_used: u64) {
    self.fbb_.push_slot::<u64>(SystemStats::VT_MEMORY_USED, memory_used, 0);
  }
  #[inline]
  pub fn add_memory_total(&mut self, memory_total: u64) {
    self.fbb_.push_slot::<u64>(SystemStats::VT_MEMORY_TOTAL, memory_total, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SystemStatsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SystemStatsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SystemStats<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SystemStats<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SystemStats");
      ds.field("cpu_usage", &self.cpu_usage());
      ds.field("memory_used", &self.memory_used());
      ds.field("memory_total", &self.memory_total());
      ds.finish()
  }
}
pub enum MonitoringPacketOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct MonitoringPacket<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for MonitoringPacket<'a> {
  type Inner = MonitoringPacket<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> MonitoringPacket<'a> {
  pub const VT_INPUT: ::flatbuffers::VOffsetT = 4;
  pub const VT_SYSTEM: ::flatbuffers::VOffsetT = 6;
  pub const VT_TIMESTAMP: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    MonitoringPacket { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MonitoringPacketArgs<'args>
  ) -> ::flatbuffers::WIPOffset<MonitoringPacket<'bldr>> {
    let mut builder = MonitoringPacketBuilder::new(_fbb);
    builder.add_timestamp(args.timestamp);
    if let Some(x) = args.system { builder.add_system(x); }
    if let Some(x) = args.input { builder.add_input(x); }
    builder.finish()
  }


  #[inline]
  pub fn input(&self) -> Option<InputStats<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<InputStats>>(MonitoringPacket::VT_INPUT, None)}
  }
  #[inline]
  pub fn system(&self) -> Option<SystemStats<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<SystemStats>>(MonitoringPacket::VT_SYSTEM, None)}
  }
  #[inline]
  pub fn timestamp(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(MonitoringPacket::VT_TIMESTAMP, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for MonitoringPacket<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<InputStats>>("input", Self::VT_INPUT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<SystemStats>>("system", Self::VT_SYSTEM, false)?
     .visit_field::<i64>("timestamp", Self::VT_TIMESTAMP, false)?
     .finish();
    Ok(())
  }
}
pub struct MonitoringPacketArgs<'a> {
    pub input: Option<::flatbuffers::WIPOffset<InputStats<'a>>>,
    pub system: Option<::flatbuffers::WIPOffset<SystemStats<'a>>>,
    pub timestamp: i64,
}
impl<'a> Default for MonitoringPacketArgs<'a> {
  #[inline]
  fn default() -> Self {
    MonitoringPacketArgs {
      input: None,
      system: None,
      timestamp: 0,
    }
  }
}

pub struct MonitoringPacketBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> MonitoringPacketBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_input(&mut self, input: ::flatbuffers::WIPOffset<InputStats<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<InputStats>>(MonitoringPacket::VT_INPUT, input);
  }
  #[inline]
  pub fn add_system(&mut self, system: ::flatbuffers::WIPOffset<SystemStats<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<SystemStats>>(MonitoringPacket::VT_SYSTEM, system);
  }
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: i64) {
    self.fbb_.push_slot::<i64>(MonitoringPacket::VT_TIMESTAMP, timestamp, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> MonitoringPacketBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MonitoringPacketBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<MonitoringPacket<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for MonitoringPacket<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("MonitoringPacket");
      ds.field("input", &self.input());
      ds.field("system", &self.system());
      ds.field("timestamp", &self.timestamp());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `MonitoringPacket`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_monitoring_packet_unchecked`.
pub fn root_as_monitoring_packet(buf: &[u8]) -> Result<MonitoringPacket<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<MonitoringPacket>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `MonitoringPacket` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_monitoring_packet_unchecked`.
pub fn size_prefixed_root_as_monitoring_packet(buf: &[u8]) -> Result<MonitoringPacket<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<MonitoringPacket>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `MonitoringPacket` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_monitoring_packet_unchecked`.
pub fn root_as_monitoring_packet_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<MonitoringPacket<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<MonitoringPacket<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `MonitoringPacket` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_monitoring_packet_unchecked`.
pub fn size_prefixed_root_as_monitoring_packet_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<MonitoringPacket<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<MonitoringPacket<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a MonitoringPacket and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `MonitoringPacket`.
pub unsafe fn root_as_monitoring_packet_unchecked(buf: &[u8]) -> MonitoringPacket<'_> {
  unsafe { ::flatbuffers::root_unchecked::<MonitoringPacket>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed MonitoringPacket and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `MonitoringPacket`.
pub unsafe fn size_prefixed_root_as_monitoring_packet_unchecked(buf: &[u8]) -> MonitoringPacket<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<MonitoringPacket>(buf) }
}
#[inline]
pub fn finish_monitoring_packet_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<MonitoringPacket<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_monitoring_packet_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<MonitoringPacket<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Monitoring
}  // pub mod Workahub

