// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library workahub.monitoring;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;



class InputStats {
  InputStats._(this._bc, this._bcOffset);
  factory InputStats(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<InputStats> reader = _InputStatsReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get mouseClicks => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get keyPresses => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 6, 0);
  int get mouseMoves => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 8, 0);

  @override
  String toString() {
    return 'InputStats{mouseClicks: ${mouseClicks}, keyPresses: ${keyPresses}, mouseMoves: ${mouseMoves}}';
  }
}

class _InputStatsReader extends fb.TableReader<InputStats> {
  const _InputStatsReader();

  @override
  InputStats createObject(fb.BufferContext bc, int offset) => 
    InputStats._(bc, offset);
}

class InputStatsBuilder {
  InputStatsBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addMouseClicks(int? mouseClicks) {
    fbBuilder.addUint64(0, mouseClicks);
    return fbBuilder.offset;
  }
  int addKeyPresses(int? keyPresses) {
    fbBuilder.addUint64(1, keyPresses);
    return fbBuilder.offset;
  }
  int addMouseMoves(int? mouseMoves) {
    fbBuilder.addUint64(2, mouseMoves);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class InputStatsObjectBuilder extends fb.ObjectBuilder {
  final int? _mouseClicks;
  final int? _keyPresses;
  final int? _mouseMoves;

  InputStatsObjectBuilder({
    int? mouseClicks,
    int? keyPresses,
    int? mouseMoves,
  })
      : _mouseClicks = mouseClicks,
        _keyPresses = keyPresses,
        _mouseMoves = mouseMoves;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(3);
    fbBuilder.addUint64(0, _mouseClicks);
    fbBuilder.addUint64(1, _keyPresses);
    fbBuilder.addUint64(2, _mouseMoves);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class SystemStats {
  SystemStats._(this._bc, this._bcOffset);
  factory SystemStats(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<SystemStats> reader = _SystemStatsReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get cpuUsage => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 4, 0.0);
  int get memoryUsed => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 6, 0);
  int get memoryTotal => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 8, 0);

  @override
  String toString() {
    return 'SystemStats{cpuUsage: ${cpuUsage}, memoryUsed: ${memoryUsed}, memoryTotal: ${memoryTotal}}';
  }
}

class _SystemStatsReader extends fb.TableReader<SystemStats> {
  const _SystemStatsReader();

  @override
  SystemStats createObject(fb.BufferContext bc, int offset) => 
    SystemStats._(bc, offset);
}

class SystemStatsBuilder {
  SystemStatsBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addCpuUsage(double? cpuUsage) {
    fbBuilder.addFloat32(0, cpuUsage);
    return fbBuilder.offset;
  }
  int addMemoryUsed(int? memoryUsed) {
    fbBuilder.addUint64(1, memoryUsed);
    return fbBuilder.offset;
  }
  int addMemoryTotal(int? memoryTotal) {
    fbBuilder.addUint64(2, memoryTotal);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class SystemStatsObjectBuilder extends fb.ObjectBuilder {
  final double? _cpuUsage;
  final int? _memoryUsed;
  final int? _memoryTotal;

  SystemStatsObjectBuilder({
    double? cpuUsage,
    int? memoryUsed,
    int? memoryTotal,
  })
      : _cpuUsage = cpuUsage,
        _memoryUsed = memoryUsed,
        _memoryTotal = memoryTotal;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(3);
    fbBuilder.addFloat32(0, _cpuUsage);
    fbBuilder.addUint64(1, _memoryUsed);
    fbBuilder.addUint64(2, _memoryTotal);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class MonitoringPacket {
  MonitoringPacket._(this._bc, this._bcOffset);
  factory MonitoringPacket(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<MonitoringPacket> reader = _MonitoringPacketReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  InputStats? get input => InputStats.reader.vTableGetNullable(_bc, _bcOffset, 4);
  SystemStats? get system => SystemStats.reader.vTableGetNullable(_bc, _bcOffset, 6);
  int get timestamp => const fb.Int64Reader().vTableGet(_bc, _bcOffset, 8, 0);

  @override
  String toString() {
    return 'MonitoringPacket{input: ${input}, system: ${system}, timestamp: ${timestamp}}';
  }
}

class _MonitoringPacketReader extends fb.TableReader<MonitoringPacket> {
  const _MonitoringPacketReader();

  @override
  MonitoringPacket createObject(fb.BufferContext bc, int offset) => 
    MonitoringPacket._(bc, offset);
}

class MonitoringPacketBuilder {
  MonitoringPacketBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addInputOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addSystemOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addTimestamp(int? timestamp) {
    fbBuilder.addInt64(2, timestamp);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class MonitoringPacketObjectBuilder extends fb.ObjectBuilder {
  final InputStatsObjectBuilder? _input;
  final SystemStatsObjectBuilder? _system;
  final int? _timestamp;

  MonitoringPacketObjectBuilder({
    InputStatsObjectBuilder? input,
    SystemStatsObjectBuilder? system,
    int? timestamp,
  })
      : _input = input,
        _system = system,
        _timestamp = timestamp;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? inputOffset = _input?.getOrCreateOffset(fbBuilder);
    final int? systemOffset = _system?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(3);
    fbBuilder.addOffset(0, inputOffset);
    fbBuilder.addOffset(1, systemOffset);
    fbBuilder.addInt64(2, _timestamp);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
